#ifndef NVIC_CONFIGURATION_H_
#define NVIC_CONFIGURATION_H_
 /*
NVIC_16_GROUP_0_SUB
NVIC_8_GROUP_2_SUB
NVIC_4_GROUP_4_SUB
NVIC_2_GROUP_8_SUB
NVIC_0_GROUP_16_SUB */

#define 	MNVIC_GRP_SUB   NVIC_4_GROUP_4_SUB
#endif

